spring:
  application:
    name: "MTGenerator"
  datasource:
    url: jdbc:h2:file:./data/mtgenerator
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

com:
  pacrombie:
    ultimatebravery:
      scryfall:
        base-url: "https://api.scryfall.com"