openapi: 3.2.0
info:
  title: MTGenerator Swagger Spec
  description: |-
    MTGenerator

  contact:
    email: curtishagan2468@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.13
paths:
  /v1:
    /deck:
      get:
        description: Get a new deck list.
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeckRequest'
          required: true
components:
  schemas:
    DeckRequest:
      type: object
      properties:
        format:
          type: string
          description: MTG format for the deck.
          enum:
            - commander
          default: commander